apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: configmap-test-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-test-sa
subjects:
- kind: ServiceAccount
  name: configmap-test
  namespace: configmap-test
