apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: configmap-test
  name: configmap-test
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: configmap-test
  type: NodePort
status:
  loadBalancer: {}
